services:
  autoware:
    image: ${AUTOWARE_JETSON_IMAGE:-ghcr.io/yonvanom/autoware:universe-jetson-devel}
    container_name: autoware-jetson
    runtime: nvidia
    init: true
    ipc: host
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ${DATA_PATH:-$HOME/autoware_data}:/autoware_data:rw
    restart: "no"
